### There are 5 numbers in the data set: (8, 12, 16, 24, 4)
 What is the mean?
 What will be the sum of deviations of individual data points from their mean?
 What is the standard deviation?

In [ ]:
Mean = (8 + 12 + 16 + 24 + 4)/5 = 12,8
Sum of deviations = (12,8 -8)^2 + (12,8 -12)^2 +.... = 23,04 +0.64+10.24 + 125,44 +77,44 = 236,8 / 5 = 47,36
standard deviation = 6,88

In [ ]:
import numpy as np
data = np.array([8, 12, 16, 24, 4])
dmean = data.mean()
print(dmean)
data.sort()
print(data)
data.std()





12.8
[ 4  8 12 16 24]


6.881860213634101

## Ex 3 : Odp. E  = A & D 

In [164]:
from scipy import stats as st
[10, 10, 10, 10, 11, 11, 12, 13, 14 ]
[15, 15, 15, 16, 16, 16, 16, 16, 17, 18, 19, 19]
[20, 20, 20, 21, 21, 21, 21, 21, 22, 22, 22, 23, 23, 23, 24, 24, 24]
data = [26, 26, 26, 26, 26, 26, 26, 27, 27, 27, 27, 29, 29, 5, 29, 29, 29, 29, 29, 29]
[30, 30, 30, 30, 30, 31, 31, 32, 32, 33, 33, 34, 34]
[35, 35, 35, 37, 37, 37, 37, 39, 39, 39]
[40, 40, 43, 43, 44, 44]
[46, 46, 46, 47, 49]
[52, 53, 54]
data = np.array(data)
data.sort()
st.mode(data)
print(st.mode(data))
print(data)

ModeResult(mode=29, count=8)
[ 5 26 26 26 26 26 26 26 27 27 27 27 29 29 29 29 29 29 29 29]


In [42]:
import math
salary = [25, 25, 25, 40, 40, 35, 50, 50, 50, 50]
salary = np.array(salary)
print(salary.mean())
for i in salary:
    x += (39-i)**2
x= x/ 10
x = math.sqrt(x)
print(x)
salary.std()



39.0
10.45695225879025


10.44030650891055

### Numpy Ex.


In [ ]:
#### 1. Import the numpy package under the name `np`
import numpy as np

#### 2. Print the numpy version and the configuration
#np.show_config()
#np.__version__

#### 3. Create a null vector of size 10 
#arr = np.zeros(10, dtype=np.int32)
#print(arr)

#### 4. How to find the memory size of any array
#arr.size
#arr.itemsize

#### 5. How to get the documentation of the numpy add function from the command line?
#print(np.info(np.add))


#### 6. Create a null vector of size 10 but the fifth value which is 1 

arr = np.zeros(10, dtype=np.int32)
arr[4] = 1
print(arr)

# using a loop
result = []
for i in range(10):
    if i == 4:
        result.append(1)
    else:
        result.append(0)

arr = np.array(result, dtype=np.int32)

# list comprehension

arr = np.array([1 if i == 4 else 0 for i in range(10)], dtype=np.int32)
print(arr)

#### 7. Create a vector with values ranging from 10 to 49

siedem = np.arange(10,49)

#### 8. Reverse a vector (first element becomes last) 

siedem = np.arange(49, 10)

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 
matryca = np.arange(0,9)
print(matryca)
matryca = matryca.reshape(3,3)
matryca

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0]
arr2 = np.array([1,2,0,0,4,0])
for i in range(len(arr2)):
    if arr2[i] != 0:
        print(i)
## indices dziala tylkodla wielowymiarowych macierzy, dla jendowymiarowych uzywamy .where lub .arange

gdzie = np.nonzero(arr2)
print(gdzie)
    
gdzie = np.where(arr2 != 0)[0]
print(gdzie)

#### 11. Create a 3x3 identity matrix - all diagonal are equal 1, the rest  0

macierz = np.eye(3,dtype = int)
macierz


#### 12. Create a 3x3x3 array with random values 

trzyd = np.random.rand(3, 3, 3)
trzyd

#### 13. Create a 10x10 array with random values and find the minimum and maximum values

nowa = np.random.rand(10,10)
nowa.max()
nowa.min()

#### 14. Create a random vector of size 30 and find the mean value 

przypadek = np.random.rand(30)
przypadek
srednia = przypadek.mean()
srednia

#### 15. Create a 2d array with 1 on the border and 0 inside 
n= 10
arr = np.zeros((n,n), dtype =np.int64)
#arr[:4,:1] = 1
#arr[:1,:4] = 1
#arr[3:,:4] = 1
#arr[1:3,3:] = 1
#arr

arr[0,:]=1
arr[-1,:] =1
arr[:,0] = 1
arr[:,-1] =1
arr


#### 16. How to add a border (filled with 0's) around an existing array?
arr = np.random.randint(10,size =(10,10)) # range, size(n,n)
pad_arr = np.pad(arr,(1,1), "linear_ramp", end_values=(0,0))
pad_arr










[0 0 0 0 1 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]
[0 1 2 3 4 5 6 7 8]
0
1
4
(array([0, 1, 4], dtype=int64),)
[0 1 4]


array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 6, 0, 4, 4, 0, 7, 9, 7, 0, 9, 0],
       [0, 0, 3, 3, 5, 0, 9, 0, 3, 0, 5, 0],
       [0, 0, 4, 9, 4, 2, 1, 3, 1, 4, 3, 0],
       [0, 8, 9, 8, 4, 9, 9, 5, 1, 1, 4, 0],
       [0, 8, 2, 9, 8, 2, 1, 8, 2, 6, 8, 0],
       [0, 8, 3, 1, 9, 0, 0, 0, 6, 8, 7, 0],
       [0, 5, 9, 5, 8, 9, 2, 0, 7, 2, 5, 0],
       [0, 5, 0, 7, 0, 3, 9, 5, 2, 2, 7, 0],
       [0, 0, 9, 8, 7, 6, 0, 2, 7, 5, 5, 0],
       [0, 7, 1, 9, 4, 5, 2, 5, 7, 7, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
#### 17. What is the result of the following expression?

0 * np.nan 
#Multiplying 0 by np.nan results in np.nan. 
#Reason: In arithmetic operations, multiplying by NaN (Not a Number) generally propagates the NaN value, since it's not a valid number and the result of any arithmetic operation with NaN is also NaN.
np.nan == np.nan # Returns False, because undefined or not a number can not equal to any value, including itself
np.inf > np.nan # Any comparison with nan is always false
np.nan - np.nan #undefined operation , so results in np.nan
np.nan in set([np.nan]) # This expression results in True.
                        # Reason: Although np.nan is not equal to np.nan, it is considered to be present in a set containing np.nan. 
                        # This is because in checks for the presence of an element in a set based on the identity of the elements, not equality. 
                        # Therefore, a set with a NaN value can contain NaN.
0.3 == 3 * 0.1 # apparently False...due to precision issues

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

diagonal_elements = np.array([1,2,3,4])
#val = np.zeros((5,5), dtype=int)
val = np.diag(diagonal_elements, k=-1)
val

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern ---wiersze[start:stop:step, kolumny]
n = 8
arr = np.zeros((n,n), dtype =np.int64)
#arr[::,1::2]= 1
#arr[1::2,::]= 1
#arr[1::2,1::2]=0
#arr

arr[1::2, ::2]=1
arr[::2, 1::2]=1
arr

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

arr = np.unravel_index(99,(6,7,8)) # ( 99, bo od zera liczymy)
#arr=np.random.randint(0,100, size=(6,7,8))
arr

#(1,5,3) czyli druga macierz, 6 wiersz i 4 kolumna (od 0 i up to but not including)

#### 21. Create a checkerboard 8x8 matrix using the tile function
arr = np.array([[0,1],[1,0]])
arr = np.tile(arr,(4,4))   # tile(A, reps) A - input array, reps - number of repetitions along each axis

#### 22. Normalize a 5x5 random matrix ---> Normalize means to adapt to another range for example [0,1]

# min/max normalization() rescaling)
arr = np.random.randint(0, 100, size=(5,5))
arr_max = arr.max()
arr_min = arr.min()

normalized = (np.subtract(arr,arr_min))/ (arr_max - arr_min)
normalized


# Z -Score normalization  - where after rescaling, every mean value is 0 and std = 1
arr_mean = arr.mean()
arr_std = arr.std()


normalized = np.subtract(arr,arr_mean) / arr_std
normalized

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA)

arr = np.dtype([("r",np.uint8), ("g", np.uint), ("b", np.uint8), ("a",np.uint8)])
colors = np.array([(255,0,0,255),(0, 255,0, 255), (0,0,255,255)], dtype = arr)  # (red, green, blue, alpha)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

arr = np.random.randint(0, 10, size = (5,3))
arr2 = np. random.randint(0, 10, size = (3,2))
multiplied = np.matmul(arr, arr2)
print(multiplied.shape)
multiplied

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place.

import numpy as np
arr = np.array([0,1,2,3,4,10,8])
new =[]
for i in arr:
    if i > 3 and i < 8:
        pass
    else:
        new.append(i)
print(new)


#### 26. What is the output of the following script?
""""
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
"""
9


#### 27. Consider an integer vector Z, which of these expressions are legal?
"""
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
"""


#### 28. What are the result of the following expressions?

"""
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
"""

#### 29. How to round away from zero a float array ?

arr = np.array([0.6,1.7,2.2,3.5,4.7,10,8])
arr2= np.ceil(arr).astype(int)
arr2

#### 30. How to find common values between two arrays? 

arr = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])

com_val = np.intersect1d(arr,arr2)
com_val




(5, 2)
[0, 1, 2, 3, 10, 8]


array([3, 4, 5])